name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 3. Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          cd Application/service-api
          docker build -t service-api:latest .
      
          - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"  # or whichever version you need
        
      - name: Install dependencies
        run: |
          cd Application/service-api
          pip install -r requirements.txt
          pip install pytest
          
      # 5. Unit tests (Python example)
      - name: Run tests
        run: |
          cd Application/service-api
          pytest --maxfail=1 --disable-warnings -q

      # 6. Scan image for vulnerabilities
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: service-api:latest
          exit-code: "0"
          format: "table"

      # 7. Upload artifact : logs, coverage, etc.
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-reports
env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
